<?php
/**
 * ApiAvailabilityStatusType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace YandexMarketApi\Model;
use \YandexMarketApi\ObjectSerializer;

/**
 * ApiAvailabilityStatusType Class Doc Comment
 *
 * @category Class
 * @description Возможность использовать API:  * &#x60;AVAILABLE&#x60; — методы API доступны для выполнения запросов. * &#x60;DISABLED_BY_INACTIVITY&#x60; — методы API недоступны из-за [неактивности магазина или кабинета](*inactivity).
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ApiAvailabilityStatusType
{
    /**
     * Possible values of this enum
     */
    public const AVAILABLE = 'AVAILABLE';

    public const DISABLED_BY_INACTIVITY = 'DISABLED_BY_INACTIVITY';

    public const DISABLED_BY_NO_ACTIVE_CONTRACT = 'DISABLED_BY_NO_ACTIVE_CONTRACT';

    public const MANUALLY_DISABLED = 'MANUALLY_DISABLED';

    public const DISABLED_BY_NO_PLACEMENT_TYPE = 'DISABLED_BY_NO_PLACEMENT_TYPE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AVAILABLE,
            self::DISABLED_BY_INACTIVITY,
            self::DISABLED_BY_NO_ACTIVE_CONTRACT,
            self::MANUALLY_DISABLED,
            self::DISABLED_BY_NO_PLACEMENT_TYPE
        ];
    }
}


