<?php
/**
 * BarcodeFormatType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace YandexMarketApi\Model;
use \YandexMarketApi\ObjectSerializer;

/**
 * BarcodeFormatType Class Doc Comment
 *
 * @category Class
 * @description Формат страницы и размер штрихкодов:  * &#x60;F_30_20&#x60; — А4, штрихкоды размера 30 × 20 мм. * &#x60;F_43_25&#x60; — А4, штрихкоды размера 43 × 25 мм. * &#x60;F_58_40&#x60; — А4, штрихкоды размера 58 × 40 мм. * &#x60;F_43_25_SINGLE&#x60; — для печати этикеток.
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BarcodeFormatType
{
    /**
     * Possible values of this enum
     */
    public const _30_20 = 'F_30_20';

    public const _43_25 = 'F_43_25';

    public const _58_40 = 'F_58_40';

    public const _43_25_SINGLE = 'F_43_25_SINGLE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_30_20,
            self::_43_25,
            self::_58_40,
            self::_43_25_SINGLE
        ];
    }
}


