<?php
/**
 * KeyIndicatorsReportDetalizationLevelType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace YandexMarketApi\Model;
use \YandexMarketApi\ObjectSerializer;

/**
 * KeyIndicatorsReportDetalizationLevelType Class Doc Comment
 *
 * @category Class
 * @description За какой период нужна детализация:  * &#x60;WEEK&#x60; — по неделям.  * &#x60;MONTH&#x60; — по месяцам.
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class KeyIndicatorsReportDetalizationLevelType
{
    /**
     * Possible values of this enum
     */
    public const WEEK = 'WEEK';

    public const MONTH = 'MONTH';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::WEEK,
            self::MONTH
        ];
    }
}


