<?php
/**
 * LabelsSortingType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace YandexMarketApi\Model;
use \YandexMarketApi\ObjectSerializer;

/**
 * LabelsSortingType Class Doc Comment
 *
 * @category Class
<<<<<<<< HEAD:lib/Model/FeedIndexLogsIndexType.php
 * @description Тип обновления.  Возможные значения:  * &#x60;DIFF&#x60; — частичное обновление данных на Яндекс Маркете (например, обновление цен ранее опубликованных предложений и публикация новых). * &#x60;FAST_PRICE&#x60; — только обновление цен ранее опубликованных предложений. * &#x60;FULL&#x60; — полное обновление данных на Яндекс Маркете.
========
 * @description Тип сортировки ярлыков:  * &#x60;SORT_BY_GIVEN_ORDER&#x60; — ярлыки заказов будут расположены в том же порядке, в каком были переданы идентификаторы заказов в запросе. * &#x60;SORT_BY_ORDER_CREATED_AT&#x60; — ярлыки будут расположены в соответствии с датой создания заказа с группировкой по магазинам.  Если параметр не указан, ярлыки сортируются по дате создания.
>>>>>>>> upstream/main:lib/Model/LabelsSortingType.php
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LabelsSortingType
{
    /**
     * Possible values of this enum
     */
    public const GIVEN_ORDER = 'SORT_BY_GIVEN_ORDER';

    public const ORDER_CREATED_AT = 'SORT_BY_ORDER_CREATED_AT';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::GIVEN_ORDER,
            self::ORDER_CREATED_AT
        ];
    }
}


