<?php
/**
 * SupplyRequestType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace YandexMarketApi\Model;
use \YandexMarketApi\ObjectSerializer;

/**
 * SupplyRequestType Class Doc Comment
 *
 * @category Class
 * @description Тип заявки:  * &#x60;SUPPLY&#x60; — поставка товаров. * &#x60;WITHDRAW&#x60; — вывоз товаров. * &#x60;UTILIZATION&#x60; — утилизация товаров.
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SupplyRequestType
{
    /**
     * Possible values of this enum
     */
    public const SUPPLY = 'SUPPLY';

    public const WITHDRAW = 'WITHDRAW';

    public const UTILIZATION = 'UTILIZATION';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SUPPLY,
            self::WITHDRAW,
            self::UTILIZATION
        ];
    }
}


