<?php
/**
 * UinSubstatusType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace YandexMarketApi\Model;
use \YandexMarketApi\ObjectSerializer;

/**
 * UinSubstatusType Class Doc Comment
 *
 * @category Class
 * @description Детализация ошибки при проверке :no-translate[УИНа].  * &#x60;UIN_MERCHANT_MISMATCH&#x60; — :no-translate[УИН] не принадлежит вашему магазину.  * &#x60;UIN_MERCHANT_UNREGISTERED&#x60; — магазин не подключен к системе :no-translate[ГИИС ДМДК].  * &#x60;UIN_NO_DATA&#x60; — :no-translate[УИН] не найден или заблокирован.  Возвращается только для статуса &#x60;FAILED&#x60;.
 * @package  YandexMarketApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UinSubstatusType
{
    /**
     * Possible values of this enum
     */
    public const MERCHANT_MISMATCH = 'UIN_MERCHANT_MISMATCH';

    public const MERCHANT_UNREGISTERED = 'UIN_MERCHANT_UNREGISTERED';

    public const NO_DATA = 'UIN_NO_DATA';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MERCHANT_MISMATCH,
            self::MERCHANT_UNREGISTERED,
            self::NO_DATA
        ];
    }
}


